### PR TITLE
Add option debug to show console.log (default is false)

### PR DESCRIPTION
**Pull request by rudacs**
He needed console.log not to run.
So I created an option to enable / disable the option.

Tranks.

### CODE REVIEW

**Comment by ontje** [comment]
hey @codeundkakao,

could you check if the reintroduced variable scoping causes any problems in our use cases and merge if it does not?

Best,
Ontje

**Comment by codeundkakao** [comment]
hi @rudacs,

thank your for the PR. The PR states that it adds an option for enabling / disabling console logs. However most of the code changes revert back arrow functions to be compatible with Node version < 4. These should probably be two separate PRs, though I am unsure if we actually need / want compatibility with Node versions < 4 ( @ontje )?

I like the debug option for switching console logs on / off itself, though I'd probably implement this slightly different from your approach. I can think of having an internal log function that sends all logs to console when debug === true. We then replace all console.log calls with calls to our own log function. This way we only need to check that condition once in the code, saving some lines and eventually keeping the code a little less cluttered.

What do you think?

**Review by codeundkakao — CHANGES_REQUESTED** [review]
Debug option is nice but should be implemented in a slightly cleaner way, so that condition needs to be checked just once in the code, e.g. in an own log function...

**Comment by rudacs** [comment]
It would be much better this way.
I can make the adjustment and send.

About Node <= 4

I had to do this tuning (which was just uploading the util.inherits up) as I embark the nodejs on low-level hardware. And it is only compatible for the moment with node 4.
If it is not possible, no problem, I take the fork and use it for my implementation.

**Comment by rudacs** [comment]
Adjusted.

**Comment by codeundkakao** [comment]
@rudacs Sorry this took a while for the actual merge to happen. Been pretty busy lately. I adjusted your PR slightly and merged afterwards. Thank you for your contribution.

**Pull request merged**
